### PR TITLE
Fixes queryAssignedNodes when querying for nodes on browsers that do …

### LINKED ISSUE #1088: TypeError: Illegal invocation error is thrown when using  queryAssignedNodes with text nodes
### Description

queryAssignedNodes throws A "TypeError: Illegal invocation" when slotted content contains text nodes.

#### Live Demo
https://webcomponents.dev/edit/FXrFMojSYzYa8eJNaJzh

#### Steps to Reproduce

1. Create `my-element` with child nodes containing text.

#### Expected Results
No error is throw

#### Actual Results
TypeError: Illegal invocation is thrown

### Browsers Affected (Haven't tested in other browsers)
- [x ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions
Uses the default/current version in https://webcomponents.dev

### PR DESCRIPTION
**Pull request by sorvell**
…have Element.matches

Fixes #1088.

### CODE REVIEW

File: src/lib/decorators.ts [hunk 1]
```diff
@@ -465,9 +465,10 @@ export function queryAssignedNodes(
         if (nodes && selector) {
           nodes = nodes.filter(
               (node) => node.nodeType === Node.ELEMENT_NODE &&
-                      (node as Element).matches ?
+                      // tslint:disable-next-line:no-any testing existence on older browsers
+                      ((node as any).matches ?
```
Comment (justinfagnani) [inline src/lib/decorators.ts:469]: Since the DOM types include `.matches` you shouldn't need the `as any` cast. Did the old code not type-check?

**Review by justinfagnani — APPROVED** [review]

**Review by kevinpschaaf — APPROVED** [review]

File: src/lib/decorators.ts [hunk 2]
```diff
@@ -465,9 +465,10 @@ export function queryAssignedNodes(
         if (nodes && selector) {
           nodes = nodes.filter(
               (node) => node.nodeType === Node.ELEMENT_NODE &&
-                      (node as Element).matches ?
-                  (node as Element).matches(selector) :
-                  legacyMatches.call(node as Element, selector));
+                  // tslint:disable-next-line:no-any testing existence on older browsers
+                  ((node as any).matches ?
```
Comment (justinfagnani) [inline src/lib/decorators.ts:469]: Still curious about this cast here. Why is it necessary?

Comment (sorvell) [reply src/lib/decorators.ts:469]: TypeScript complains that the check is unnecessary because`matches` always exists. The previous code probably didn't analyze path.
