### PR TITLE
Ensure attribute reflected from property is correct

### LINKED ISSUE #592: Boolean Attribute no longer reflected after adding and removing the attribute
### Description
Boolean type's "reflect attribute" does not work if you manually setAttribute, and removeAttribute, without setting a default value for the boolean property.

#### Live Demo
https://stackblitz.com/edit/lit-element-example-wdqbfc?file=index.js

#### Steps to Reproduce
The attached example shows adding an attribute called "disabled", removing an attribute called "disabled", and then setting the property "disabled" to true.

The result is the disabled property is set to true, but the attribute "disabled" does not appear on the element.

#### Expected Results
Expected that the attribute "disabled" would appear on the element.

#### Actual Results
Attribute "disabled" does not appear on the element.

It appears this can be resolved by setting this.disabled = false, in the constructor.  
I see that the documentation now has the following comment:
"If you implement a static properties getter, initialize your property values in the element constructor." 

Is initializing all property values now required?  If so, the warning his helpful, but it might make sense to do a bit more - like explain what happens if you don't heed the warning.

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [?] Edge
- [?] Safari 11
- [X] Safari 10
- [?] IE 11

### Versions
- lit-element: v2.0.0-rc.2
- webcomponents: v2.2.3

### PR DESCRIPTION
**Pull request by sorvell**
Fixes #592. Ensures a reflecting property set immediately after a corresponding attribute reflects correctly.

### CODE REVIEW

File: src/lib/updating-element.ts [hunk 1]
```diff
@@ -579,24 +579,29 @@ export abstract class UpdatingElement extends HTMLElement {
...
   requestUpdate(name?: PropertyKey, oldValue?: unknown) {
     let shouldRequestUpdate = true;
-    // if we have a property key, perform property update steps.
-    if (name !== undefined && !this._changedProperties.has(name)) {
+    // If we have a property key, perform property update steps.
+    if (name !== undefined) {
       const ctor = this.constructor as typeof UpdatingElement;
       const options =
           ctor._classProperties!.get(name) || defaultPropertyDeclaration;
       if (ctor._valueHasChanged(
```
Comment (kevinpschaaf) [inline src/lib/updating-element.ts]: Unrelated to PR, but why do we pass `options.hasChanged` through a static method that just calls it?  It's private so it can't be overridden by user...

File: src/lib/updating-element.ts [hunk 2]
```diff
@@ -579,24 +579,29 @@ export abstract class UpdatingElement extends HTMLElement {
...
               this[name as keyof this], oldValue, options.hasChanged)) {
-        // track old value when changing.
-        this._changedProperties.set(name, oldValue);
-        // add to reflecting properties set
+        // Track old value when changing.
```
Comment (justinfagnani) [inline src/lib/updating-element.ts]: nit: This reads more like a "what" comment than a "why". It'd be nice to either say why we only record the once, or remove the comment since the code seems pretty self-documenting on what it's doing.

File: src/lib/updating-element.ts [hunk 3]
```diff
@@ -579,24 +579,29 @@ export abstract class UpdatingElement extends HTMLElement {
...
+        // attribute + property reflects correctly.
         if (options.reflect === true &&
             !(this._updateState & STATE_IS_REFLECTING_TO_PROPERTY)) {
           if (this._reflectingProperties === undefined) {
             this._reflectingProperties = new Map();
           }
           this._reflectingProperties.set(name, options);
         }
-        // abort the request if the property should not be considered changed.
+        // Abort the request if the property should not be considered changed.
```
Comment (justinfagnani) [inline src/lib/updating-element.ts]: what line is this commenting? The last line of the if case or the else case?

File: src/lib/updating-element.ts (hunk 1 above)
Comment (sorvell) [reply src/lib/updating-element.ts]: I believe we intend to make this overridable at some point.
